### ISSUE TITLE
Play! Encoding

### ISSUE THREAD

**Issue by aaccurso** [mbmihura/vestaro#1]
Buenas gente,

Estaba desarrollando un form para el Item y me encontré con que Play! sólo soporta encoding UTF-8 (lo cuál está bueno), pero el Eclipse no guarda los archivos en UTF-8, sino en ANSI, por lo tanto para ver los 'caracteres raros' que caracterizan a nuestro idioma español es necesario tranformar aquellos archivos fuentes en los que usemos nuestro idioma (por ejemplo en las vistas).
Yo lo transformé con Notepad ++, pero no se si habrá alguna forma de que Eclipse (sí, me vendí a Eclipse jaja) lo haga automáticamente, no me puse a investigar.

Saludos!

**Comment by mbmihura** [comment]
jajaj acabo de pasarme a intelliJ version full y  que todos hayan huido de
este ide me esta haciendo pensar que me estoy metiendo en algo feo jajaj..
por que lo dejaste?

**Comment by aaccurso** [comment]
Jajaja no, el tema es que se me actualizó el plugin de Scala y ya no me reconoce la sintaxis de los templates y otras cosas más :-1: 
Pero en cuanto a ide, me gusta mucho más que Eclipse.
Conclusión, no updatees el plugin de Scala jaja

**Comment by mbmihura** [comment]
respuesta breve: ups

PD: naty estaba teniendo un problema muy similar con que le rezconosca
metodos especificos del framework en la vista con el eclipse, no se en que
quedo

**Comment by aaccurso** [comment]
Ahí encontré como se cambia el encoding en Eclipse:
Window -> Preferences -> General -> Workspace : Text file encoding -> UTF-8
