### ISSUE TITLE
Dashboard Loading

### ISSUE THREAD

**Issue by mbmihura** [mbmihura/vestaro#24]
Cuando se accede al dashboard a traves de un link (o en cualquier otra situación donde no se carge la pagina entera) no se cargan los graficos. Ver imagen mas abajo. 
Si se abre una nueva pestaña con la url de dashboards (se carga la pagina entera de cero), anda todo bien.

![image](https://f.cloud.github.com/assets/950167/1405448/e0c458d2-3d2b-11e3-9532-23b26831c185.png)

![image](https://f.cloud.github.com/assets/950167/1405451/23718056-3d2c-11e3-91f7-700151b67f45.png)

**Comment by aaccurso** [comment]
Encontré esto:
http://www.amcharts.com/forum/viewtopic.php?id=9398

Parece que no es necesario usar Amcharts.ready() cuando el dataset lo generás a partir de una llamada ajax.

Recién hice un fix en 820878b2adbb6964c5e6ebbe278641a3271c6a7f

@nadalpablo cuando puedas fijate que esté todo ok, yo lo probé un toque y parece que anda todo bien.

Saludos!
