### ISSUE TITLE
YAML ids

### ISSUE THREAD

**Issue by aaccurso** [mbmihura/vestaro#53]
Acabo de descubrir una cosa.

Ayer Nati no podía agregar acciones porque las acciones que cargamos al comienzo a partir del yml tienen hardcodeados el id, por lo tanto no tienen que recurrir al sequence de la base para obtener el próximo id y por ende no se actualiza el mismo (el sequence es el que nos da el próximo valor de una columna serial/identity). Entonces al querer agregar una nueva acción el sequence devolvía id = 1 que ya estaba cargado en la base y como consecuencia fallaba por duplicate key.

Ahora lo que pensaba es que debe estar pasando lo mismo con otras entidades, como por ejemplo Collection, en la cual le hardcodeamos el id.

Conclusión, probé de borrar los ids hardcodeados de las entidades cargadas con el yml y ahí SI usa el sequence ya que no le estamos pasando el id. Por lo tanto mi propuesta es la siguiente:
- Borrar los ids de las entidades Action, Collection y Stock.
- Ponerle un Tag a las Collections para así poder referenciarlas desde los Items (No es necesario para Action y Stock porque no las referenciamos en otra entidad).

Eso es todo.
Les quería avisar así me dan el ok, lo modifico y pusheo.

Saludos!

**Comment by mbmihura** [comment]
Por favor todavia no.. no los modifiques!

**Comment by aaccurso** [comment]
Dale, por eso estaba avisando :P

**Comment by mbmihura** [comment]
Ahora si, ya pushee los cambios. No etendi bien lo del Tag? Cual seria la
idea?

2013/11/10 aaccurso notifications@github.com

**Comment by aaccurso** [comment]
Sería como están los users y los sellers que tienen &userAlan &ropaCool
para después referenciarlos como {seller: *userAlan} y así evitar usar ids
estáticos.

2013/11/10 mbmihura notifications@github.com

**Comment by mbmihura** [comment]
Ah.. habia entendi en el modelo.. si dale por mi si!

por otro lado, hay una clase mockStock.. se puede eliminar? creo que la
usa/usaba naty

2013/11/10 aaccurso notifications@github.com

**Comment by natponzo** [comment]
Yo no cree esa clase, que yo recuerde, tal vez borracha (?).

Con lo otro me parece bien, sino va a empezar a aparecer el problema con el
resto de las entities.  Entonces lo que decís es que si en el archivo
inicial cargás las entidades sin los ids los genera solos?
No se cómo es bien lo de los tags, eso vale solo para el archivo sólo? es
decir, después programáticamente no le vamos a agregar tags a las entidades
que creemos,no?

**Comment by mbmihura** [comment]
Perfecto, entonces se va..

si los de los tag es a nivel archivo yml.. si se eliminan los ids se
necesita un forma de referenciar, para poder crear relaciones entre
objetos, ahora seria usando tag.

Con los ids de las prendas (que se usarían en la url para referenciarlas),
deberían ser numéricos.. si quedan como están actualmente con string (por
ej, 'CB1') el sistema no puede generarlos, y pedírselos al usuario es
desubicado jajaj. Si van a ser numéricos también habría que eliminar los
ids del yml porque volveríamos al problema que dice Alan.

**Comment by aaccurso** [comment]
Lo de los tags es sólo a nivel carga inicial del yml. El scope es el
archivo yaml. Lo voy a hacer para las entidades que dije más arriba:
Collection, Stock y Action.
En un rato me pongo a hacerlo, estaba viendo de meterle masonry a la
búsqueda de items, está quedando piola (lo que sea para no ponerme con apit
jajaja).
Cualquier cosa me avisan.

**Comment by aaccurso** [comment]
Recién lo probé creando una nueva collection y tiró PK violation. Fuck.

**Comment by aaccurso** [comment]
Ah no, SI ANDA!!
Lo que pasaba es que Pablín hacía algo raro jaja
collection.id = Long.parseLong(((Integer) (findCollectionsOwnedBy(1L).size() + 1)).toString());
Listo, issue solucionado.
