### ISSUE TITLE
No anda el flujo de compra en DEV

### ISSUE THREAD

**Issue by aaccurso** [mbmihura/vestaro#54]
Hola estaba por probar el refactor que hice de YAML haciendo una compra, pero parece que pasó algo, porque ahora cuando se hace click en 'Pagar..' aparece un backdrop de un modal y no hace nada.
Lo pueden revisar los que pushearon últimos?
Gracias!

**Comment by natponzo** [comment]
OK, ahora miro

**Comment by aaccurso** [comment]
miralo en la branch que creé de YAML-Refactor así tmb probás que se pueda
crear una Action :p

**Comment by aaccurso** [comment]
Kurt tmb lo está mirando

**Comment by mbmihura** [comment]
hay un anchor con un href="#" que hace que vaya al home. Por otro lado, el data togle que se dispara no existe, por eso solo muestra la pagina opacada.
Ya estoy armando un fix, ahora lo pusheo

**Comment by natponzo** [comment]
en dónde? no se d qué están hablando jaja

**Comment by mbmihura** [comment]
en la vista de BuyItem.scala...

Lamento informar que el fix no anda, me voy a poner bien con esto.. proximamente mas novedades

**Comment by aaccurso** [comment]
Pasa lo mismo en los accordions de 'Ordenes de Compra' en 'Perfil' del
comprador. Tienen un href=#.

2013/11/10 mbmihura notifications@github.com

**Comment by mbmihura** [comment]
opc A: revisamos todos los href="#"
opc B: volvemos a 1.0.8

como prefieran

**Comment by aaccurso** [comment]
Por qué revisar? Con eliminar no alcanza? Yo lo hago, con un IDE copado
todo se hace más fácil jaja

**Comment by aaccurso** [comment]
Recién revisé, los dos únicos lugares donde aparece son: Pagar y Ordenes de
Compra.
El de pagar lo eliminé porque estaba al pedo, el de ordenes lo usa
bootstrap para gestionar los accordions.
Lo reviso.

2013/11/10 Alan Accurso accurso.alan@gmail.com

> Por qué revisar? Con eliminar no alcanza? Yo lo hago, con un IDE copado
> todo se hace más fácil jaja
>

**Comment by aaccurso** [comment]
Listo, cambié el href por un data-target. Aguante bootstrap.

**Comment by natponzo** [comment]
Bueeena!

2013/11/10 aaccurso notifications@github.com
